import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#fff8f4',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#410007',
        'surface-dim': '#e1d8d2',
        'surface': '#fff8f4',
        'on-secondary-container': '#66645f',
        'surface-container-low': '#fbf2eb',
        'surface-container-highest': '#eae1db',
        'on-surface-variant': '#444748',
        'on-background': '#1f1b17',
        'on-surface': '#1f1b17',
        'surface-variant': '#eae1db',
        'on-secondary-fixed-variant': '#484742',
        'error-container': '#ffdad6',
        'primary-fixed': '#e5e2e1',
        'primary': '#000000',
        'on-primary-container': '#858383',
        'on-tertiary-container': '#f1414d',
        'outline': '#747878',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-container-high': '#efe7e0',
        'secondary': '#605e59',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f8efe9',
        'surface-tint': '#5f5e5e',
        'secondary-container': '#e6e2db',
        'primary-container': '#1c1b1b',
        'surface-container': '#f5ece6',
        'background': '#fff8f4',
        'inverse-primary': '#c8c6c5',
        'on-secondary-fixed': '#1c1c18',
        'inverse-surface': '#34302b',
        'outline-variant': '#c4c7c7',
        'accent-coral': '#f1414d',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      spacing: {
        'grid-margin': '4rem',
        'grid-gutter': '1.5rem',
        'section-gap': '8rem',
        'stack-sm': '0.5rem',
        'stack-md': '1.5rem',
      },
      fontFamily: {
        newsreader: ['var(--font-newsreader)', 'serif'],
        'work-sans': ['var(--font-work-sans)', 'sans-serif'],
        'display-xl': ['var(--font-newsreader)', 'serif'],
        'headline-lg': ['var(--font-newsreader)', 'serif'],
        'headline-md': ['var(--font-newsreader)', 'serif'],
        'body-lg': ['var(--font-work-sans)', 'sans-serif'],
        'body-md': ['var(--font-work-sans)', 'sans-serif'],
        'label-caps': ['var(--font-work-sans)', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      maxWidth: {
        editorial: '1440px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}

export default config
